export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';
export const INCREMENT_ASYNC_REQUEST = 'INCREMENT_ASYNC_REQUEST';
export const INCREMENT_ASYNC_SUCCESS = 'INCREMENT_ASYNC_SUCCESS';
